/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\kt2_common.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kt2_common.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-9.348, 2.106, -3.374]}>
        <mesh geometry={nodes.Body2.geometry} material={materials.Metal_espresso_mashine} position={[5.448, 1.412, -0.327]} />
        <mesh geometry={nodes.Body__e001.geometry} material={materials.Black_aspirator} position={[5.704, 1.233, -0.011]} />
        <mesh geometry={nodes.Body_cofee_espresso_maker.geometry} material={materials.Black_aspirator} position={[5.534, 1.31, -0.327]} />
        <mesh geometry={nodes.Box001.geometry} material={materials['Kitchen base material']} position={[5.78, 2.355, 0.195]} />
        <mesh geometry={nodes.Box002.geometry} material={materials['Kitchen base material']} position={[5.782, 2.352, 2.951]} />
        <mesh geometry={nodes.Box003.geometry} material={materials['Kitchen base material']} position={[5.678, 0.656, -0.079]} />
        <mesh geometry={nodes.Box004.geometry} material={materials['Kitchen base material']} position={[5.678, 0.656, 2.699]} />
        <mesh geometry={nodes.Box005.geometry} material={materials['Kitchen base material']} position={[5.68, 0.656, 1.308]} />
        <mesh geometry={nodes.Box006.geometry} material={materials['Kitchen base material']} position={[5.655, 1.334, 3.924]} />
        <mesh geometry={nodes.Box007.geometry} material={materials['Kitchen base material']} position={[2.424, -2.168, -8.93]} />
        <mesh geometry={nodes.Box008.geometry} material={materials['Kitchen base material']} position={[-0.092, 0.678, 1.557]} />
        <mesh geometry={nodes.Box009.geometry} material={materials['Kitchen base material']} position={[2.424, -2.168, -8.93]} />
        <mesh geometry={nodes.Box010.geometry} material={materials['Kitchen base material']} position={[-0.095, 0.656, -0.102]} />
        <mesh geometry={nodes.Box011Built_in_oven.geometry} material={materials['Built in oven']} position={[5.606, 1.549, 3.922]} />
        <mesh geometry={nodes.Box02.geometry} material={materials.Aspirator} position={[5.691, 2.298, 1.879]} />
        <mesh geometry={nodes.Box03.geometry} material={materials.Aspirator} position={[5.689, 2.874, 1.881]} />
        <mesh geometry={nodes.Box080.geometry} material={materials.Aspirator} position={[5.689, 2.148, 1.879]} />
        <mesh geometry={nodes.Button.geometry} material={materials.Black_aspirator} position={[5.436, 1.439, -0.318]} />
        <mesh geometry={nodes.Button001.geometry} material={materials.Black_aspirator} position={[5.44, 1.408, -0.294]} />
        <mesh geometry={nodes.Cap_coofee_espresso.geometry} material={materials.Black_aspirator} position={[5.629, 1.463, -0.327]} />
        <mesh geometry={nodes.Capsule002003.geometry} material={materials.Chrome_pot} position={[5.703, 1.238, 0.016]} />
        <mesh geometry={nodes.Coffee_pot.geometry} material={materials.Ceramic} position={[5.654, 1.239, 0.135]} />
        <mesh geometry={nodes.Coffee_pot001.geometry} material={materials.Ceramic} position={[5.654, 1.239, 0.219]} />
        <mesh geometry={nodes.Coffee_pot002.geometry} material={materials.Ceramic} position={[5.654, 1.239, 0.291]} />
        <mesh geometry={nodes.Coffee_pot003.geometry} material={materials.Ceramic} position={[5.58, 1.239, 0.133]} />
        <mesh geometry={nodes.Coffee_pot004.geometry} material={materials.Ceramic} position={[5.576, 1.239, 0.214]} />
        <mesh geometry={nodes.Coffee_pot005.geometry} material={materials.Ceramic} position={[5.575, 1.239, 0.291]} />
        <mesh geometry={nodes.Cooper_pot_handle.geometry} material={materials.Chrome} position={[5.551, 1.332, 1.357]} />
        <mesh geometry={nodes.Curve003.geometry} material={nodes.Curve003.material} position={[5.46, 1.348, -0.261]} />
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.RMetal} position={[5.48, 1.35, -0.328]} />
        <mesh geometry={nodes.Cylinder012.geometry} material={materials.Black_aspirator} position={[5.465, 1.32, -0.25]} />
        <mesh geometry={nodes.Cylinder02.geometry} material={materials.Black_aspirator} position={[5.421, 1.352, -0.362]} />
        <mesh geometry={nodes.Cylinder04.geometry} material={materials.Glass} position={[5.542, 2.123, 1.673]} />
        <mesh geometry={nodes.Cylinder04001.geometry} material={materials.Glass} position={[5.542, 2.123, 2.111]} />
        <mesh geometry={nodes.Cylinder04002.geometry} material={materials.Glass} position={[5.846, 2.123, 1.885]} />
        <mesh geometry={nodes.Cylinder07.geometry} material={materials.Chrome} position={[5.542, 2.136, 1.66]} />
        <mesh geometry={nodes.Cylinder07001.geometry} material={materials.Chrome} position={[5.542, 2.136, 2.097]} />
        <mesh geometry={nodes.Cylinder07002.geometry} material={materials.Chrome} position={[5.846, 2.136, 1.886]} />
        <mesh geometry={nodes.Cylinder_e001.geometry} material={materials.Black_aspirator} position={[5.703, 1.237, 0.01]} />
        <mesh geometry={nodes.CylinderLight001.geometry} material={materials.Light_ceiling} position={[4.228, 3.377, 2.591]} />
        <mesh geometry={nodes.CylinderLight002.geometry} material={materials.Light_ceiling} position={[4.228, 3.377, 1.533]} />
        <mesh geometry={nodes.CylinderLight003.geometry} material={materials.Light_ceiling} position={[4.228, 3.377, 0.521]} />
        <mesh geometry={nodes.CylinderLight004.geometry} material={materials.Light_ceiling} position={[4.228, 3.377, -0.514]} />
        <mesh geometry={nodes.CylinderLight005.geometry} material={materials.Light_ceiling} position={[1.518, 3.377, 3.806]} />
        <mesh geometry={nodes.CylinderLight006.geometry} material={materials.Light_ceiling} position={[1.518, 3.377, 2.591]} />
        <mesh geometry={nodes.CylinderLight007.geometry} material={materials.Light_ceiling} position={[1.518, 3.377, 1.533]} />
        <mesh geometry={nodes.CylinderLight008.geometry} material={materials.Light_ceiling} position={[4.228, 3.377, 3.806]} />
        <mesh geometry={nodes.CylinderLight009.geometry} material={materials.Light_ceiling} position={[1.518, 3.377, 0.521]} />
        <mesh geometry={nodes.CylinderLight010.geometry} material={materials.Light_ceiling} position={[1.518, 3.377, -0.514]} />
        <mesh geometry={nodes.Floor.geometry} material={materials.Floor} position={[2.816, 0.048, 1.626]} />
        <mesh geometry={nodes.Glass_jar.geometry} material={materials.Glass} position={[-0.074, 1.222, 1.525]} />
        <mesh geometry={nodes.Induction_cooktop.geometry} material={nodes.Induction_cooktop.material} position={[5.575, 1.225, 1.933]} />
        <mesh geometry={nodes.Induction_cooktop001.geometry} material={materials['Induction Cooktop']} position={[5.567, 1.236, 1.933]} />
        <mesh geometry={nodes.Kitchen_base_01.geometry} material={materials['Base kitchen']} position={[5.631, 0.11, 1.666]} />
        <mesh geometry={nodes.Kitchen_base_02.geometry} material={materials['Base kitchen']} position={[-0.054, 0.108, 0.759]} />
        <mesh geometry={nodes.Kitchen_light_01.geometry} material={materials['Kitchen light']} position={[5.749, 1.969, -0.764]} />
        <mesh geometry={nodes.Kitchen_light_02.geometry} material={materials['Kitchen light']} position={[5.749, 1.969, 2.567]} />
        <mesh geometry={nodes.Kitchen_light_03.geometry} material={materials['Kitchen light']} position={[-0.135, 1.948, 0.756]} />
        <mesh geometry={nodes.Kitchen_worktop_01.geometry} material={materials['Material worktop']} position={[5.583, 1.192, 1.291]} />
        <mesh geometry={nodes.Kitchen_worktop_02.geometry} material={materials['Material worktop']} position={[-0.007, 1.188, 0.83]} />
        <mesh geometry={nodes.Leg_coffee_espresso_maker.geometry} material={materials['Black.001']} position={[5.472, 1.224, -0.267]} />
        <mesh geometry={nodes.Leg_coffee_espresso_maker001.geometry} material={materials['Black.001']} position={[5.472, 1.224, -0.391]} />
        <mesh geometry={nodes.Leg_coffee_espresso_maker002.geometry} material={materials['Black.001']} position={[5.585, 1.224, -0.391]} />
        <mesh geometry={nodes.Leg_coffee_espresso_maker003.geometry} material={materials['Black.001']} position={[5.585, 1.224, -0.263]} />
        <mesh geometry={nodes.Leg_refrigerator.geometry} material={materials.Black} position={[-0.266, 0.087, 2.543]} />
        <mesh geometry={nodes.Leg_refrigerator001.geometry} material={materials.Black} position={[0.251, 0.087, 2.543]} />
        <mesh geometry={nodes.Leg_refrigerator002.geometry} material={materials.Black} position={[-0.266, 0.087, 3.237]} />
        <mesh geometry={nodes.Leg_refrigerator003.geometry} material={materials.Black} position={[0.251, 0.087, 3.237]} />
        <mesh geometry={nodes.Light_on_ceiling001.geometry} material={materials.Chrome} position={[4.229, 3.394, 2.592]} />
        <mesh geometry={nodes.Light_on_ceiling002.geometry} material={materials.Chrome} position={[4.229, 3.394, 1.534]} />
        <mesh geometry={nodes.Light_on_ceiling003.geometry} material={materials.Chrome} position={[4.229, 3.394, 0.522]} />
        <mesh geometry={nodes.Light_on_ceiling004.geometry} material={materials.Chrome} position={[4.229, 3.394, -0.513]} />
        <mesh geometry={nodes.Light_on_ceiling005.geometry} material={materials.Chrome} position={[1.519, 3.394, 3.807]} />
        <mesh geometry={nodes.Light_on_ceiling006.geometry} material={materials.Chrome} position={[1.519, 3.394, 2.592]} />
        <mesh geometry={nodes.Light_on_ceiling007.geometry} material={materials.Chrome} position={[1.519, 3.394, 1.534]} />
        <mesh geometry={nodes.Light_on_ceiling008.geometry} material={materials.Chrome} position={[4.229, 3.394, 3.807]} />
        <mesh geometry={nodes.Light_on_ceiling009.geometry} material={materials.Chrome} position={[1.519, 3.394, 0.522]} />
        <mesh geometry={nodes.Light_on_ceiling010.geometry} material={materials.Chrome} position={[1.519, 3.394, -0.513]} />
        <mesh geometry={nodes.Line002_Mesh343.geometry} material={materials.Black_table} position={[-0.006, 1.285, -0.679]} />
        <mesh geometry={nodes.Line03.geometry} material={materials.Chrome_pot} position={[5.482, 1.337, -0.328]} />
        <mesh geometry={nodes.Line194.geometry} material={materials.Black} position={[5.555, 1.391, 1.355]} />
        <mesh geometry={nodes.Plate_coffee.geometry} material={materials.Ceramic} position={[5.658, 1.228, 0.131]} />
        <mesh geometry={nodes.Plate_coffee001.geometry} material={materials.Ceramic} position={[5.658, 1.228, 0.218]} />
        <mesh geometry={nodes.Plate_coffee002.geometry} material={materials.Ceramic} position={[5.658, 1.228, 0.29]} />
        <mesh geometry={nodes.Plate_coffee003.geometry} material={materials.Ceramic} position={[5.579, 1.228, 0.131]} />
        <mesh geometry={nodes.Plate_coffee004.geometry} material={materials.Ceramic} position={[5.579, 1.228, 0.211]} />
        <mesh geometry={nodes.Plate_coffee005.geometry} material={materials.Ceramic} position={[5.579, 1.228, 0.29]} />
        <mesh geometry={nodes.Pot_big2.geometry} material={materials.Chrome} position={[5.554, 1.372, 1.356]} />
        <mesh geometry={nodes.REd2.geometry} material={materials.Metal_espresso_mashine} position={[5.448, 1.249, -0.327]} />
        <mesh geometry={nodes.Refrigerator_handle.geometry} material={materials['Chrome.001']} position={[0.465, 1.151, 3.05]} />
        <mesh geometry={nodes.Refrigerator_handle001.geometry} material={materials['Chrome.001']} position={[0.465, 0.921, 3.05]} />
        <mesh geometry={nodes.Retopo_Cable_coffee_machine.geometry} material={materials.Black_aspirator} position={[5.7, 1.234, -0.175]} />
        <mesh geometry={nodes.Retopo_Door001.geometry} material={materials['Material.001']} position={[5.57, 2.356, -0.368]} />
        <mesh geometry={nodes.Retopo_Door003.geometry} material={materials['Material.001']} position={[0.012, 2.356, 1.858]} />
        <mesh geometry={nodes.Retopo_Door004.geometry} material={materials['Material.001']} position={[5.319, 2.349, 4.297]} />
        <mesh geometry={nodes.Retopo_Door005001.geometry} material={materials['Material.001']} position={[5.312, 0.656, -0.362]} />
        <mesh geometry={nodes.Retopo_Door005002.geometry} material={materials['Material.001']} position={[0.274, 0.656, 1.845]} />
        <mesh geometry={nodes.Retopo_Door009.geometry} material={materials['Material.001']} position={[5.322, 0.656, 4.294]} />
        <mesh geometry={nodes.Retopo_Door015.geometry} material={materials['Material.001']} position={[5.57, 2.356, 2.977]} />
        <group position={[5.906, 1.5, 0.784]}>
          <mesh geometry={nodes.mesh009.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh009_1.geometry} material={materials.Black_Outlet} />
        </group>
        <group position={[5.906, 1.5, -0.361]}>
          <mesh geometry={nodes.mesh010.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh010_1.geometry} material={materials.Black_Outlet} />
        </group>
        <group position={[5.906, 1.5, -0.441]}>
          <mesh geometry={nodes.mesh011.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh011_1.geometry} material={materials.Black_Outlet} />
        </group>
        <group position={[5.906, 1.5, 3.15]}>
          <mesh geometry={nodes.mesh012.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh012_1.geometry} material={materials.Black_Outlet} />
        </group>
        <group position={[5.906, 1.5, 3.07]}>
          <mesh geometry={nodes.mesh013.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh013_1.geometry} material={materials.Black_Outlet} />
        </group>
        <group position={[-0.33, 1.5, 1.881]}>
          <mesh geometry={nodes.mesh014.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh014_1.geometry} material={materials.Black_Outlet} />
        </group>
        <group position={[-0.33, 1.5, 1.961]}>
          <mesh geometry={nodes.mesh015.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh015_1.geometry} material={materials.Black_Outlet} />
        </group>
        <group position={[-0.33, 1.5, -0.629]}>
          <mesh geometry={nodes.mesh016.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh016_1.geometry} material={materials.Black_Outlet} />
        </group>
        <group position={[-0.33, 1.5, -0.55]}>
          <mesh geometry={nodes.mesh017.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh017_1.geometry} material={materials.Black_Outlet} />
        </group>
        <group position={[5.906, 1.5, 0.864]}>
          <mesh geometry={nodes.mesh008.geometry} material={materials['White outlet']} />
          <mesh geometry={nodes.mesh008_1.geometry} material={materials.Black_Outlet} />
        </group>
        <mesh geometry={nodes.Retopo_Pot_big.geometry} material={materials.Chrome} position={[5.555, 1.305, 1.357]} />
        <mesh geometry={nodes.Retopo_Rectangle01001_Mesh341.geometry} material={materials['metal.001']} position={[-0.199, 1.314, -0.449]} />
        <mesh geometry={nodes.Retopo_Rectangle01_Mesh338.geometry} material={materials['metal.001']} position={[-0.187, 1.314, -0.905]} />
        <mesh geometry={nodes.Retopo_Refrigerator.geometry} material={materials.Refrigerator} position={[0.125, 1.235, 2.873]} />
        <mesh geometry={nodes.Rmetal.geometry} material={materials.RMetal} position={[5.481, 1.269, -0.33]} />
        <mesh geometry={nodes.Saucer.geometry} material={materials.Saucer} position={[5.613, 1.226, 0.218]} />
        <mesh geometry={nodes.Shape01_Mesh337.geometry} material={materials.Metal_gray} position={[-0.167, 1.308, -0.678]} />
        <mesh geometry={nodes.Shape02_Mesh342.geometry} material={materials.Metal_gray} position={[-0.073, 1.353, -0.68]} />
        <mesh geometry={nodes.Sink.geometry} material={materials['Sink metal']} position={[-0.004, 1.137, 1.036]} />
        <mesh geometry={nodes.Sphere133.geometry} material={nodes.Sphere133.material} position={[5.385, 1.352, -0.383]} />
        <mesh geometry={nodes.Tiles_on_the_wall_01.geometry} material={materials['Tiles on the wall']} position={[5.918, 1.001, 1.129]} />
        <mesh geometry={nodes.Tiles_on_the_wall_02.geometry} material={materials['Tiles on the wall']} position={[-0.34, 1.035, 0.715]} />
        <mesh geometry={nodes.White_reservoar.geometry} material={materials.Reservoar_plastic} position={[5.629, 1.403, -0.327]} />
      </group>
      <group position={[-6.925, 2.568, -1.621]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material worktop']} />
      </group>
    </group>
  )
}

useGLTF.preload('/kt2_common.gltf')
